controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_newwork:
    path: /principal/newwork
    controller: App\Controller\PrincipalController::newwork
   