controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_principal:
    path: /principal
    controller: App\Controller\PrincipalController::show

app_newwork:
    path: /principal/newwork
    controller: App\Controller\PrincipalController::newwork
   
app_newpers:
    path: /principal/newpers
    controller: App\Controller\PrincipalController::newpers

   