controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_principal:
    path: /principal
    controller: App\Controller\PrincipalController::show

app_newwork:
    path: /principal/newwork
    controller: App\Controller\PrincipalController::newwork
   
app_newpers:
    path: /principal/newpers
    controller: App\Controller\PrincipalController::newpers

app_dismiss:
    path: /principal/dismiss/{persID}
    controller: App\Controller\PrincipalController::dismiss
            
app_office:
    path: /office
    controller: App\Controller\OfficeController::index
       
app_saveoffice:
    path: /office/save
    controller: App\Controller\OfficeController::save
   